// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_protos.proto

package com.zwl.protocolbuffer;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<com.zwl.protocolbuffer.Person> 
      getPersonList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  com.zwl.protocolbuffer.Person getPerson(int index);
  /**
   * <code>repeated .Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<? extends com.zwl.protocolbuffer.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  com.zwl.protocolbuffer.PersonOrBuilder getPersonOrBuilder(
      int index);
}
