// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_protos.proto

package com.zwl.protocolbuffer;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zwl_protocolbuffer_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zwl_protocolbuffer_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zwl_protocolbuffer_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zwl_protocolbuffer_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zwl_protocolbuffer_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zwl_protocolbuffer_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024address_protos.proto\022\026com.zwl.protocol" +
      "buffer\"\367\001\n\006Person\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 " +
      "\001(\005\022\r\n\005email\030\003 \001(\t\022:\n\006phones\030\004 \003(\0132*.com" +
      ".zwl.protocolbuffer.Person.PhoneNumber\032[" +
      "\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t\022<\n\004type\030\002 " +
      "\001(\0162(.com.zwl.protocolbuffer.Person.Phon" +
      "eType:\004home\"+\n\tPhoneType\022\n\n\006mobile\020\000\022\010\n\004" +
      "home\020\001\022\010\n\004work\020\002\"=\n\013AddressBook\022.\n\006perso" +
      "n\030\001 \003(\0132\036.com.zwl.protocolbuffer.PersonB" +
      "6\n\026com.zwl.protocolbufferB\021AddressBookPr" +
      "otosP\001\210\001\001\240\001\001\330\001\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zwl_protocolbuffer_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zwl_protocolbuffer_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zwl_protocolbuffer_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", });
    internal_static_com_zwl_protocolbuffer_Person_PhoneNumber_descriptor =
      internal_static_com_zwl_protocolbuffer_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_zwl_protocolbuffer_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zwl_protocolbuffer_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
    internal_static_com_zwl_protocolbuffer_AddressBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zwl_protocolbuffer_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zwl_protocolbuffer_AddressBook_descriptor,
        new java.lang.String[] { "Person", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
