// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package com.zwl.protocolbuffer;

public final class AllNormalTypes {
  private AllNormalTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zwl_protocolbuffer_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zwl_protocolbuffer_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zwl_protocolbuffer_ProtoDemo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zwl_protocolbuffer_ProtoDemo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zwl_protocolbuffer_ProtoDemo_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zwl_protocolbuffer_ProtoDemo_MapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDemo.proto\022\026com.zwl.protocolbuffer\032\031go" +
      "ogle/protobuf/any.proto\032\037google/protobuf" +
      "/timestamp.proto\032\036google/protobuf/durati" +
      "on.proto\"U\n\006Result\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030" +
      "\002 \001(\t\0220\n\004type\030\003 \001(\0162\".com.zwl.protocolbu" +
      "ffer.ResultType\"\267\004\n\tProtoDemo\022\r\n\005int32\030\001" +
      " \001(\005\022\r\n\005int64\030\002 \001(\003\022\016\n\006sint32\030\003 \001(\021\022\016\n\006s" +
      "int64\030\004 \001(\022\022\016\n\006uint32\030\005 \001(\r\022\016\n\006uint64\030\006 " +
      "\001(\004\022\r\n\005float\030\007 \001(\002\022\016\n\006double\030\010 \001(\001\022\017\n\007fi" +
      "xed32\030\t \001(\007\022\017\n\007fixed64\030\n \001(\006\022\020\n\010sfixed32" +
      "\030\013 \001(\017\022\020\n\010sfixed64\030\014 \001(\020\022\014\n\004bool\030\r \001(\010\022\013" +
      "\n\003str\030\016 \001(\t\022\r\n\005bytes\030\017 \001(\014\022\016\n\004name\030\020 \001(\t" +
      "H\000\022\r\n\003age\030\021 \001(\005H\000\0227\n\003map\030\022 \003(\0132*.com.zwl" +
      ".protocolbuffer.ProtoDemo.MapEntry\022/\n\007re" +
      "sults\030\023 \003(\0132\036.com.zwl.protocolbuffer.Res" +
      "ult\022%\n\007details\030\024 \003(\0132\024.google.protobuf.A" +
      "ny\022-\n\ttimestamp\030\025 \001(\0132\032.google.protobuf." +
      "Timestamp\022+\n\010duration\030\026 \001(\0132\031.google.pro" +
      "tobuf.Duration\032*\n\010MapEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\003:\0028\001B\005\n\003one*2\n\nResultType\022" +
      "\013\n\007success\020\000\022\010\n\004fail\020\001\022\r\n\texception\020\002B3\n" +
      "\026com.zwl.protocolbufferB\016AllNormalTypesP" +
      "\001\210\001\001\240\001\001\330\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_com_zwl_protocolbuffer_Result_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zwl_protocolbuffer_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zwl_protocolbuffer_Result_descriptor,
        new java.lang.String[] { "Code", "Msg", "Type", });
    internal_static_com_zwl_protocolbuffer_ProtoDemo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zwl_protocolbuffer_ProtoDemo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zwl_protocolbuffer_ProtoDemo_descriptor,
        new java.lang.String[] { "Int32", "Int64", "Sint32", "Sint64", "Uint32", "Uint64", "Float", "Double", "Fixed32", "Fixed64", "Sfixed32", "Sfixed64", "Bool", "Str", "Bytes", "Name", "Age", "Map", "Results", "Details", "Timestamp", "Duration", "One", });
    internal_static_com_zwl_protocolbuffer_ProtoDemo_MapEntry_descriptor =
      internal_static_com_zwl_protocolbuffer_ProtoDemo_descriptor.getNestedTypes().get(0);
    internal_static_com_zwl_protocolbuffer_ProtoDemo_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zwl_protocolbuffer_ProtoDemo_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
