// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address_protos.proto

package com.zwl.protocolbuffer;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   *名称
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <pre>
   **
   *名称
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   **
   *名称
   * </pre>
   *
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   **
   *用户id
   * </pre>
   *
   * <code>optional int32 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   **
   *用户id
   * </pre>
   *
   * <code>optional int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <pre>
   **
   *邮箱
   * </pre>
   *
   * <code>optional string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <pre>
   **
   *邮箱
   * </pre>
   *
   * <code>optional string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   **
   *邮箱
   * </pre>
   *
   * <code>optional string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   **
   *手机
   * </pre>
   *
   * <code>repeated .Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<com.zwl.protocolbuffer.Person.PhoneNumber> 
      getPhonesList();
  /**
   * <pre>
   **
   *手机
   * </pre>
   *
   * <code>repeated .Person.PhoneNumber phones = 4;</code>
   */
  com.zwl.protocolbuffer.Person.PhoneNumber getPhones(int index);
  /**
   * <pre>
   **
   *手机
   * </pre>
   *
   * <code>repeated .Person.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <pre>
   **
   *手机
   * </pre>
   *
   * <code>repeated .Person.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends com.zwl.protocolbuffer.Person.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <pre>
   **
   *手机
   * </pre>
   *
   * <code>repeated .Person.PhoneNumber phones = 4;</code>
   */
  com.zwl.protocolbuffer.Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
