// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package com.zwl.protocolbuffer;

/**
 * Protobuf type {@code com.zwl.protocolbuffer.ProtoDemo}
 */
public final class ProtoDemo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.zwl.protocolbuffer.ProtoDemo)
    ProtoDemoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoDemo.newBuilder() to construct.
  private ProtoDemo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoDemo() {
    str_ = "";
    bytes_ = com.google.protobuf.ByteString.EMPTY;
    results_ = java.util.Collections.emptyList();
    details_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoDemo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoDemo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            int32_ = input.readInt32();
            break;
          }
          case 16: {

            int64_ = input.readInt64();
            break;
          }
          case 24: {

            sint32_ = input.readSInt32();
            break;
          }
          case 32: {

            sint64_ = input.readSInt64();
            break;
          }
          case 40: {

            uint32_ = input.readUInt32();
            break;
          }
          case 48: {

            uint64_ = input.readUInt64();
            break;
          }
          case 61: {

            float_ = input.readFloat();
            break;
          }
          case 65: {

            double_ = input.readDouble();
            break;
          }
          case 77: {

            fixed32_ = input.readFixed32();
            break;
          }
          case 81: {

            fixed64_ = input.readFixed64();
            break;
          }
          case 93: {

            sfixed32_ = input.readSFixed32();
            break;
          }
          case 97: {

            sfixed64_ = input.readSFixed64();
            break;
          }
          case 104: {

            bool_ = input.readBool();
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            str_ = s;
            break;
          }
          case 122: {

            bytes_ = input.readBytes();
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();
            oneCase_ = 16;
            one_ = s;
            break;
          }
          case 136: {
            oneCase_ = 17;
            one_ = input.readInt32();
            break;
          }
          case 146: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              map_ = com.google.protobuf.MapField.newMapField(
                  MapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
            map__ = input.readMessage(
                MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            map_.getMutableMap().put(
                map__.getKey(), map__.getValue());
            break;
          }
          case 154: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              results_ = new java.util.ArrayList<com.zwl.protocolbuffer.Result>();
              mutable_bitField0_ |= 0x00000002;
            }
            results_.add(
                input.readMessage(com.zwl.protocolbuffer.Result.parser(), extensionRegistry));
            break;
          }
          case 162: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              details_ = new java.util.ArrayList<com.google.protobuf.Any>();
              mutable_bitField0_ |= 0x00000004;
            }
            details_.add(
                input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
            break;
          }
          case 170: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 178: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (duration_ != null) {
              subBuilder = duration_.toBuilder();
            }
            duration_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(duration_);
              duration_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        results_ = java.util.Collections.unmodifiableList(results_);
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        details_ = java.util.Collections.unmodifiableList(details_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zwl.protocolbuffer.AllNormalTypes.internal_static_com_zwl_protocolbuffer_ProtoDemo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 18:
        return internalGetMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zwl.protocolbuffer.AllNormalTypes.internal_static_com_zwl_protocolbuffer_ProtoDemo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zwl.protocolbuffer.ProtoDemo.class, com.zwl.protocolbuffer.ProtoDemo.Builder.class);
  }

  private int oneCase_ = 0;
  private java.lang.Object one_;
  public enum OneCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NAME(16),
    AGE(17),
    ONE_NOT_SET(0);
    private final int value;
    private OneCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OneCase valueOf(int value) {
      return forNumber(value);
    }

    public static OneCase forNumber(int value) {
      switch (value) {
        case 16: return NAME;
        case 17: return AGE;
        case 0: return ONE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public OneCase
  getOneCase() {
    return OneCase.forNumber(
        oneCase_);
  }

  public static final int INT32_FIELD_NUMBER = 1;
  private int int32_;
  /**
   * <code>int32 int32 = 1;</code>
   * @return The int32.
   */
  @java.lang.Override
  public int getInt32() {
    return int32_;
  }

  public static final int INT64_FIELD_NUMBER = 2;
  private long int64_;
  /**
   * <code>int64 int64 = 2;</code>
   * @return The int64.
   */
  @java.lang.Override
  public long getInt64() {
    return int64_;
  }

  public static final int SINT32_FIELD_NUMBER = 3;
  private int sint32_;
  /**
   * <code>sint32 sint32 = 3;</code>
   * @return The sint32.
   */
  @java.lang.Override
  public int getSint32() {
    return sint32_;
  }

  public static final int SINT64_FIELD_NUMBER = 4;
  private long sint64_;
  /**
   * <code>sint64 sint64 = 4;</code>
   * @return The sint64.
   */
  @java.lang.Override
  public long getSint64() {
    return sint64_;
  }

  public static final int UINT32_FIELD_NUMBER = 5;
  private int uint32_;
  /**
   * <code>uint32 uint32 = 5;</code>
   * @return The uint32.
   */
  @java.lang.Override
  public int getUint32() {
    return uint32_;
  }

  public static final int UINT64_FIELD_NUMBER = 6;
  private long uint64_;
  /**
   * <code>uint64 uint64 = 6;</code>
   * @return The uint64.
   */
  @java.lang.Override
  public long getUint64() {
    return uint64_;
  }

  public static final int FLOAT_FIELD_NUMBER = 7;
  private float float_;
  /**
   * <code>float float = 7;</code>
   * @return The float.
   */
  @java.lang.Override
  public float getFloat() {
    return float_;
  }

  public static final int DOUBLE_FIELD_NUMBER = 8;
  private double double_;
  /**
   * <code>double double = 8;</code>
   * @return The double.
   */
  @java.lang.Override
  public double getDouble() {
    return double_;
  }

  public static final int FIXED32_FIELD_NUMBER = 9;
  private int fixed32_;
  /**
   * <pre>
   *存储空间固定的数字类型
   * </pre>
   *
   * <code>fixed32 fixed32 = 9;</code>
   * @return The fixed32.
   */
  @java.lang.Override
  public int getFixed32() {
    return fixed32_;
  }

  public static final int FIXED64_FIELD_NUMBER = 10;
  private long fixed64_;
  /**
   * <code>fixed64 fixed64 = 10;</code>
   * @return The fixed64.
   */
  @java.lang.Override
  public long getFixed64() {
    return fixed64_;
  }

  public static final int SFIXED32_FIELD_NUMBER = 11;
  private int sfixed32_;
  /**
   * <code>sfixed32 sfixed32 = 11;</code>
   * @return The sfixed32.
   */
  @java.lang.Override
  public int getSfixed32() {
    return sfixed32_;
  }

  public static final int SFIXED64_FIELD_NUMBER = 12;
  private long sfixed64_;
  /**
   * <code>sfixed64 sfixed64 = 12;</code>
   * @return The sfixed64.
   */
  @java.lang.Override
  public long getSfixed64() {
    return sfixed64_;
  }

  public static final int BOOL_FIELD_NUMBER = 13;
  private boolean bool_;
  /**
   * <code>bool bool = 13;</code>
   * @return The bool.
   */
  @java.lang.Override
  public boolean getBool() {
    return bool_;
  }

  public static final int STR_FIELD_NUMBER = 14;
  private volatile java.lang.Object str_;
  /**
   * <code>string str = 14;</code>
   * @return The str.
   */
  @java.lang.Override
  public java.lang.String getStr() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <code>string str = 14;</code>
   * @return The bytes for str.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrBytes() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BYTES_FIELD_NUMBER = 15;
  private com.google.protobuf.ByteString bytes_;
  /**
   * <code>bytes bytes = 15;</code>
   * @return The bytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBytes() {
    return bytes_;
  }

  public static final int NAME_FIELD_NUMBER = 16;
  /**
   * <code>string name = 16;</code>
   * @return Whether the name field is set.
   */
  public boolean hasName() {
    return oneCase_ == 16;
  }
  /**
   * <code>string name = 16;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = "";
    if (oneCase_ == 16) {
      ref = one_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (oneCase_ == 16) {
        one_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string name = 16;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = "";
    if (oneCase_ == 16) {
      ref = one_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (oneCase_ == 16) {
        one_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 17;
  /**
   * <code>int32 age = 17;</code>
   * @return Whether the age field is set.
   */
  @java.lang.Override
  public boolean hasAge() {
    return oneCase_ == 17;
  }
  /**
   * <code>int32 age = 17;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    if (oneCase_ == 17) {
      return (java.lang.Integer) one_;
    }
    return 0;
  }

  public static final int MAP_FIELD_NUMBER = 18;
  private static final class MapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.zwl.protocolbuffer.AllNormalTypes.internal_static_com_zwl_protocolbuffer_ProtoDemo_MapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Long> map_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
  internalGetMap() {
    if (map_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapDefaultEntryHolder.defaultEntry);
    }
    return map_;
  }

  public int getMapCount() {
    return internalGetMap().getMap().size();
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */

  @java.lang.Override
  public boolean containsMap(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getMap() {
    return getMapMap();
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Long> getMapMap() {
    return internalGetMap().getMap();
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */
  @java.lang.Override

  public long getMapOrDefault(
      java.lang.String key,
      long defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */
  @java.lang.Override

  public long getMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int RESULTS_FIELD_NUMBER = 19;
  private java.util.List<com.zwl.protocolbuffer.Result> results_;
  /**
   * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
   */
  @java.lang.Override
  public java.util.List<com.zwl.protocolbuffer.Result> getResultsList() {
    return results_;
  }
  /**
   * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zwl.protocolbuffer.ResultOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
   */
  @java.lang.Override
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
   */
  @java.lang.Override
  public com.zwl.protocolbuffer.Result getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
   */
  @java.lang.Override
  public com.zwl.protocolbuffer.ResultOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  public static final int DETAILS_FIELD_NUMBER = 20;
  private java.util.List<com.google.protobuf.Any> details_;
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Any> getDetailsList() {
    return details_;
  }
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDetailsOrBuilderList() {
    return details_;
  }
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  @java.lang.Override
  public int getDetailsCount() {
    return details_.size();
  }
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Any getDetails(int index) {
    return details_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
      int index) {
    return details_.get(index);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 21;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 21;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 21;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 21;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int DURATION_FIELD_NUMBER = 22;
  private com.google.protobuf.Duration duration_;
  /**
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return Whether the duration field is set.
   */
  @java.lang.Override
  public boolean hasDuration() {
    return duration_ != null;
  }
  /**
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return The duration.
   */
  @java.lang.Override
  public com.google.protobuf.Duration getDuration() {
    return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
  }
  /**
   * <code>.google.protobuf.Duration duration = 22;</code>
   */
  @java.lang.Override
  public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
    return getDuration();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (int32_ != 0) {
      output.writeInt32(1, int32_);
    }
    if (int64_ != 0L) {
      output.writeInt64(2, int64_);
    }
    if (sint32_ != 0) {
      output.writeSInt32(3, sint32_);
    }
    if (sint64_ != 0L) {
      output.writeSInt64(4, sint64_);
    }
    if (uint32_ != 0) {
      output.writeUInt32(5, uint32_);
    }
    if (uint64_ != 0L) {
      output.writeUInt64(6, uint64_);
    }
    if (float_ != 0F) {
      output.writeFloat(7, float_);
    }
    if (double_ != 0D) {
      output.writeDouble(8, double_);
    }
    if (fixed32_ != 0) {
      output.writeFixed32(9, fixed32_);
    }
    if (fixed64_ != 0L) {
      output.writeFixed64(10, fixed64_);
    }
    if (sfixed32_ != 0) {
      output.writeSFixed32(11, sfixed32_);
    }
    if (sfixed64_ != 0L) {
      output.writeSFixed64(12, sfixed64_);
    }
    if (bool_ != false) {
      output.writeBool(13, bool_);
    }
    if (!getStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, str_);
    }
    if (!bytes_.isEmpty()) {
      output.writeBytes(15, bytes_);
    }
    if (oneCase_ == 16) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, one_);
    }
    if (oneCase_ == 17) {
      output.writeInt32(
          17, (int)((java.lang.Integer) one_));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMap(),
        MapDefaultEntryHolder.defaultEntry,
        18);
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(19, results_.get(i));
    }
    for (int i = 0; i < details_.size(); i++) {
      output.writeMessage(20, details_.get(i));
    }
    if (timestamp_ != null) {
      output.writeMessage(21, getTimestamp());
    }
    if (duration_ != null) {
      output.writeMessage(22, getDuration());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (int32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, int32_);
    }
    if (int64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, int64_);
    }
    if (sint32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, sint32_);
    }
    if (sint64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt64Size(4, sint64_);
    }
    if (uint32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, uint32_);
    }
    if (uint64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, uint64_);
    }
    if (float_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, float_);
    }
    if (double_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, double_);
    }
    if (fixed32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(9, fixed32_);
    }
    if (fixed64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(10, fixed64_);
    }
    if (sfixed32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed32Size(11, sfixed32_);
    }
    if (sfixed64_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeSFixed64Size(12, sfixed64_);
    }
    if (bool_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, bool_);
    }
    if (!getStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, str_);
    }
    if (!bytes_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(15, bytes_);
    }
    if (oneCase_ == 16) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, one_);
    }
    if (oneCase_ == 17) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            17, (int)((java.lang.Integer) one_));
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
         : internalGetMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
      map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(18, map__);
    }
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, results_.get(i));
    }
    for (int i = 0; i < details_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, details_.get(i));
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getTimestamp());
    }
    if (duration_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, getDuration());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zwl.protocolbuffer.ProtoDemo)) {
      return super.equals(obj);
    }
    com.zwl.protocolbuffer.ProtoDemo other = (com.zwl.protocolbuffer.ProtoDemo) obj;

    if (getInt32()
        != other.getInt32()) return false;
    if (getInt64()
        != other.getInt64()) return false;
    if (getSint32()
        != other.getSint32()) return false;
    if (getSint64()
        != other.getSint64()) return false;
    if (getUint32()
        != other.getUint32()) return false;
    if (getUint64()
        != other.getUint64()) return false;
    if (java.lang.Float.floatToIntBits(getFloat())
        != java.lang.Float.floatToIntBits(
            other.getFloat())) return false;
    if (java.lang.Double.doubleToLongBits(getDouble())
        != java.lang.Double.doubleToLongBits(
            other.getDouble())) return false;
    if (getFixed32()
        != other.getFixed32()) return false;
    if (getFixed64()
        != other.getFixed64()) return false;
    if (getSfixed32()
        != other.getSfixed32()) return false;
    if (getSfixed64()
        != other.getSfixed64()) return false;
    if (getBool()
        != other.getBool()) return false;
    if (!getStr()
        .equals(other.getStr())) return false;
    if (!getBytes()
        .equals(other.getBytes())) return false;
    if (!internalGetMap().equals(
        other.internalGetMap())) return false;
    if (!getResultsList()
        .equals(other.getResultsList())) return false;
    if (!getDetailsList()
        .equals(other.getDetailsList())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (hasDuration() != other.hasDuration()) return false;
    if (hasDuration()) {
      if (!getDuration()
          .equals(other.getDuration())) return false;
    }
    if (!getOneCase().equals(other.getOneCase())) return false;
    switch (oneCase_) {
      case 16:
        if (!getName()
            .equals(other.getName())) return false;
        break;
      case 17:
        if (getAge()
            != other.getAge()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INT32_FIELD_NUMBER;
    hash = (53 * hash) + getInt32();
    hash = (37 * hash) + INT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInt64());
    hash = (37 * hash) + SINT32_FIELD_NUMBER;
    hash = (53 * hash) + getSint32();
    hash = (37 * hash) + SINT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSint64());
    hash = (37 * hash) + UINT32_FIELD_NUMBER;
    hash = (53 * hash) + getUint32();
    hash = (37 * hash) + UINT64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUint64());
    hash = (37 * hash) + FLOAT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFloat());
    hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDouble()));
    hash = (37 * hash) + FIXED32_FIELD_NUMBER;
    hash = (53 * hash) + getFixed32();
    hash = (37 * hash) + FIXED64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFixed64());
    hash = (37 * hash) + SFIXED32_FIELD_NUMBER;
    hash = (53 * hash) + getSfixed32();
    hash = (37 * hash) + SFIXED64_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSfixed64());
    hash = (37 * hash) + BOOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBool());
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    hash = (37 * hash) + BYTES_FIELD_NUMBER;
    hash = (53 * hash) + getBytes().hashCode();
    if (!internalGetMap().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMap().hashCode();
    }
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    if (getDetailsCount() > 0) {
      hash = (37 * hash) + DETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getDetailsList().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    if (hasDuration()) {
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration().hashCode();
    }
    switch (oneCase_) {
      case 16:
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        break;
      case 17:
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zwl.protocolbuffer.ProtoDemo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zwl.protocolbuffer.ProtoDemo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.zwl.protocolbuffer.ProtoDemo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.zwl.protocolbuffer.ProtoDemo)
      com.zwl.protocolbuffer.ProtoDemoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zwl.protocolbuffer.AllNormalTypes.internal_static_com_zwl_protocolbuffer_ProtoDemo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 18:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 18:
          return internalGetMutableMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zwl.protocolbuffer.AllNormalTypes.internal_static_com_zwl_protocolbuffer_ProtoDemo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zwl.protocolbuffer.ProtoDemo.class, com.zwl.protocolbuffer.ProtoDemo.Builder.class);
    }

    // Construct using com.zwl.protocolbuffer.ProtoDemo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultsFieldBuilder();
        getDetailsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      int32_ = 0;

      int64_ = 0L;

      sint32_ = 0;

      sint64_ = 0L;

      uint32_ = 0;

      uint64_ = 0L;

      float_ = 0F;

      double_ = 0D;

      fixed32_ = 0;

      fixed64_ = 0L;

      sfixed32_ = 0;

      sfixed64_ = 0L;

      bool_ = false;

      str_ = "";

      bytes_ = com.google.protobuf.ByteString.EMPTY;

      internalGetMutableMap().clear();
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        resultsBuilder_.clear();
      }
      if (detailsBuilder_ == null) {
        details_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        detailsBuilder_.clear();
      }
      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      if (durationBuilder_ == null) {
        duration_ = null;
      } else {
        duration_ = null;
        durationBuilder_ = null;
      }
      oneCase_ = 0;
      one_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zwl.protocolbuffer.AllNormalTypes.internal_static_com_zwl_protocolbuffer_ProtoDemo_descriptor;
    }

    @java.lang.Override
    public com.zwl.protocolbuffer.ProtoDemo getDefaultInstanceForType() {
      return com.zwl.protocolbuffer.ProtoDemo.getDefaultInstance();
    }

    @java.lang.Override
    public com.zwl.protocolbuffer.ProtoDemo build() {
      com.zwl.protocolbuffer.ProtoDemo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zwl.protocolbuffer.ProtoDemo buildPartial() {
      com.zwl.protocolbuffer.ProtoDemo result = new com.zwl.protocolbuffer.ProtoDemo(this);
      int from_bitField0_ = bitField0_;
      result.int32_ = int32_;
      result.int64_ = int64_;
      result.sint32_ = sint32_;
      result.sint64_ = sint64_;
      result.uint32_ = uint32_;
      result.uint64_ = uint64_;
      result.float_ = float_;
      result.double_ = double_;
      result.fixed32_ = fixed32_;
      result.fixed64_ = fixed64_;
      result.sfixed32_ = sfixed32_;
      result.sfixed64_ = sfixed64_;
      result.bool_ = bool_;
      result.str_ = str_;
      result.bytes_ = bytes_;
      if (oneCase_ == 16) {
        result.one_ = one_;
      }
      if (oneCase_ == 17) {
        result.one_ = one_;
      }
      result.map_ = internalGetMap();
      result.map_.makeImmutable();
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
      if (detailsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          details_ = java.util.Collections.unmodifiableList(details_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.details_ = details_;
      } else {
        result.details_ = detailsBuilder_.build();
      }
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      if (durationBuilder_ == null) {
        result.duration_ = duration_;
      } else {
        result.duration_ = durationBuilder_.build();
      }
      result.oneCase_ = oneCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zwl.protocolbuffer.ProtoDemo) {
        return mergeFrom((com.zwl.protocolbuffer.ProtoDemo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zwl.protocolbuffer.ProtoDemo other) {
      if (other == com.zwl.protocolbuffer.ProtoDemo.getDefaultInstance()) return this;
      if (other.getInt32() != 0) {
        setInt32(other.getInt32());
      }
      if (other.getInt64() != 0L) {
        setInt64(other.getInt64());
      }
      if (other.getSint32() != 0) {
        setSint32(other.getSint32());
      }
      if (other.getSint64() != 0L) {
        setSint64(other.getSint64());
      }
      if (other.getUint32() != 0) {
        setUint32(other.getUint32());
      }
      if (other.getUint64() != 0L) {
        setUint64(other.getUint64());
      }
      if (other.getFloat() != 0F) {
        setFloat(other.getFloat());
      }
      if (other.getDouble() != 0D) {
        setDouble(other.getDouble());
      }
      if (other.getFixed32() != 0) {
        setFixed32(other.getFixed32());
      }
      if (other.getFixed64() != 0L) {
        setFixed64(other.getFixed64());
      }
      if (other.getSfixed32() != 0) {
        setSfixed32(other.getSfixed32());
      }
      if (other.getSfixed64() != 0L) {
        setSfixed64(other.getSfixed64());
      }
      if (other.getBool() != false) {
        setBool(other.getBool());
      }
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        onChanged();
      }
      if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
        setBytes(other.getBytes());
      }
      internalGetMutableMap().mergeFrom(
          other.internalGetMap());
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000002);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      if (detailsBuilder_ == null) {
        if (!other.details_.isEmpty()) {
          if (details_.isEmpty()) {
            details_ = other.details_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDetailsIsMutable();
            details_.addAll(other.details_);
          }
          onChanged();
        }
      } else {
        if (!other.details_.isEmpty()) {
          if (detailsBuilder_.isEmpty()) {
            detailsBuilder_.dispose();
            detailsBuilder_ = null;
            details_ = other.details_;
            bitField0_ = (bitField0_ & ~0x00000004);
            detailsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDetailsFieldBuilder() : null;
          } else {
            detailsBuilder_.addAllMessages(other.details_);
          }
        }
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.hasDuration()) {
        mergeDuration(other.getDuration());
      }
      switch (other.getOneCase()) {
        case NAME: {
          oneCase_ = 16;
          one_ = other.one_;
          onChanged();
          break;
        }
        case AGE: {
          setAge(other.getAge());
          break;
        }
        case ONE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zwl.protocolbuffer.ProtoDemo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zwl.protocolbuffer.ProtoDemo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int oneCase_ = 0;
    private java.lang.Object one_;
    public OneCase
        getOneCase() {
      return OneCase.forNumber(
          oneCase_);
    }

    public Builder clearOne() {
      oneCase_ = 0;
      one_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int int32_ ;
    /**
     * <code>int32 int32 = 1;</code>
     * @return The int32.
     */
    @java.lang.Override
    public int getInt32() {
      return int32_;
    }
    /**
     * <code>int32 int32 = 1;</code>
     * @param value The int32 to set.
     * @return This builder for chaining.
     */
    public Builder setInt32(int value) {
      
      int32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 int32 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt32() {
      
      int32_ = 0;
      onChanged();
      return this;
    }

    private long int64_ ;
    /**
     * <code>int64 int64 = 2;</code>
     * @return The int64.
     */
    @java.lang.Override
    public long getInt64() {
      return int64_;
    }
    /**
     * <code>int64 int64 = 2;</code>
     * @param value The int64 to set.
     * @return This builder for chaining.
     */
    public Builder setInt64(long value) {
      
      int64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 int64 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64() {
      
      int64_ = 0L;
      onChanged();
      return this;
    }

    private int sint32_ ;
    /**
     * <code>sint32 sint32 = 3;</code>
     * @return The sint32.
     */
    @java.lang.Override
    public int getSint32() {
      return sint32_;
    }
    /**
     * <code>sint32 sint32 = 3;</code>
     * @param value The sint32 to set.
     * @return This builder for chaining.
     */
    public Builder setSint32(int value) {
      
      sint32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 sint32 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSint32() {
      
      sint32_ = 0;
      onChanged();
      return this;
    }

    private long sint64_ ;
    /**
     * <code>sint64 sint64 = 4;</code>
     * @return The sint64.
     */
    @java.lang.Override
    public long getSint64() {
      return sint64_;
    }
    /**
     * <code>sint64 sint64 = 4;</code>
     * @param value The sint64 to set.
     * @return This builder for chaining.
     */
    public Builder setSint64(long value) {
      
      sint64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint64 sint64 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSint64() {
      
      sint64_ = 0L;
      onChanged();
      return this;
    }

    private int uint32_ ;
    /**
     * <code>uint32 uint32 = 5;</code>
     * @return The uint32.
     */
    @java.lang.Override
    public int getUint32() {
      return uint32_;
    }
    /**
     * <code>uint32 uint32 = 5;</code>
     * @param value The uint32 to set.
     * @return This builder for chaining.
     */
    public Builder setUint32(int value) {
      
      uint32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 uint32 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint32() {
      
      uint32_ = 0;
      onChanged();
      return this;
    }

    private long uint64_ ;
    /**
     * <code>uint64 uint64 = 6;</code>
     * @return The uint64.
     */
    @java.lang.Override
    public long getUint64() {
      return uint64_;
    }
    /**
     * <code>uint64 uint64 = 6;</code>
     * @param value The uint64 to set.
     * @return This builder for chaining.
     */
    public Builder setUint64(long value) {
      
      uint64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 uint64 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUint64() {
      
      uint64_ = 0L;
      onChanged();
      return this;
    }

    private float float_ ;
    /**
     * <code>float float = 7;</code>
     * @return The float.
     */
    @java.lang.Override
    public float getFloat() {
      return float_;
    }
    /**
     * <code>float float = 7;</code>
     * @param value The float to set.
     * @return This builder for chaining.
     */
    public Builder setFloat(float value) {
      
      float_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float float = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloat() {
      
      float_ = 0F;
      onChanged();
      return this;
    }

    private double double_ ;
    /**
     * <code>double double = 8;</code>
     * @return The double.
     */
    @java.lang.Override
    public double getDouble() {
      return double_;
    }
    /**
     * <code>double double = 8;</code>
     * @param value The double to set.
     * @return This builder for chaining.
     */
    public Builder setDouble(double value) {
      
      double_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double double = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDouble() {
      
      double_ = 0D;
      onChanged();
      return this;
    }

    private int fixed32_ ;
    /**
     * <pre>
     *存储空间固定的数字类型
     * </pre>
     *
     * <code>fixed32 fixed32 = 9;</code>
     * @return The fixed32.
     */
    @java.lang.Override
    public int getFixed32() {
      return fixed32_;
    }
    /**
     * <pre>
     *存储空间固定的数字类型
     * </pre>
     *
     * <code>fixed32 fixed32 = 9;</code>
     * @param value The fixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed32(int value) {
      
      fixed32_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *存储空间固定的数字类型
     * </pre>
     *
     * <code>fixed32 fixed32 = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed32() {
      
      fixed32_ = 0;
      onChanged();
      return this;
    }

    private long fixed64_ ;
    /**
     * <code>fixed64 fixed64 = 10;</code>
     * @return The fixed64.
     */
    @java.lang.Override
    public long getFixed64() {
      return fixed64_;
    }
    /**
     * <code>fixed64 fixed64 = 10;</code>
     * @param value The fixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setFixed64(long value) {
      
      fixed64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed64 fixed64 = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearFixed64() {
      
      fixed64_ = 0L;
      onChanged();
      return this;
    }

    private int sfixed32_ ;
    /**
     * <code>sfixed32 sfixed32 = 11;</code>
     * @return The sfixed32.
     */
    @java.lang.Override
    public int getSfixed32() {
      return sfixed32_;
    }
    /**
     * <code>sfixed32 sfixed32 = 11;</code>
     * @param value The sfixed32 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed32(int value) {
      
      sfixed32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed32 sfixed32 = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed32() {
      
      sfixed32_ = 0;
      onChanged();
      return this;
    }

    private long sfixed64_ ;
    /**
     * <code>sfixed64 sfixed64 = 12;</code>
     * @return The sfixed64.
     */
    @java.lang.Override
    public long getSfixed64() {
      return sfixed64_;
    }
    /**
     * <code>sfixed64 sfixed64 = 12;</code>
     * @param value The sfixed64 to set.
     * @return This builder for chaining.
     */
    public Builder setSfixed64(long value) {
      
      sfixed64_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sfixed64 sfixed64 = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfixed64() {
      
      sfixed64_ = 0L;
      onChanged();
      return this;
    }

    private boolean bool_ ;
    /**
     * <code>bool bool = 13;</code>
     * @return The bool.
     */
    @java.lang.Override
    public boolean getBool() {
      return bool_;
    }
    /**
     * <code>bool bool = 13;</code>
     * @param value The bool to set.
     * @return This builder for chaining.
     */
    public Builder setBool(boolean value) {
      
      bool_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearBool() {
      
      bool_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object str_ = "";
    /**
     * <code>string str = 14;</code>
     * @return The str.
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string str = 14;</code>
     * @return The bytes for str.
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string str = 14;</code>
     * @param value The str to set.
     * @return This builder for chaining.
     */
    public Builder setStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      str_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string str = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearStr() {
      
      str_ = getDefaultInstance().getStr();
      onChanged();
      return this;
    }
    /**
     * <code>string str = 14;</code>
     * @param value The bytes for str to set.
     * @return This builder for chaining.
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      str_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes = 15;</code>
     * @return The bytes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }
    /**
     * <code>bytes bytes = 15;</code>
     * @param value The bytes to set.
     * @return This builder for chaining.
     */
    public Builder setBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes bytes = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearBytes() {
      
      bytes_ = getDefaultInstance().getBytes();
      onChanged();
      return this;
    }

    /**
     * <code>string name = 16;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return oneCase_ == 16;
    }
    /**
     * <code>string name = 16;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = "";
      if (oneCase_ == 16) {
        ref = one_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (oneCase_ == 16) {
          one_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 16;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = "";
      if (oneCase_ == 16) {
        ref = one_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (oneCase_ == 16) {
          one_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 16;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  oneCase_ = 16;
      one_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      if (oneCase_ == 16) {
        oneCase_ = 0;
        one_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string name = 16;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      oneCase_ = 16;
      one_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 age = 17;</code>
     * @return Whether the age field is set.
     */
    public boolean hasAge() {
      return oneCase_ == 17;
    }
    /**
     * <code>int32 age = 17;</code>
     * @return The age.
     */
    public int getAge() {
      if (oneCase_ == 17) {
        return (java.lang.Integer) one_;
      }
      return 0;
    }
    /**
     * <code>int32 age = 17;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      oneCase_ = 17;
      one_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      if (oneCase_ == 17) {
        oneCase_ = 0;
        one_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> map_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetMutableMap() {
      onChanged();;
      if (map_ == null) {
        map_ = com.google.protobuf.MapField.newMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      if (!map_.isMutable()) {
        map_ = map_.copy();
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18;</code>
     */

    @java.lang.Override
    public boolean containsMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getMap() {
      return getMapMap();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Long> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18;</code>
     */
    @java.lang.Override

    public long getMapOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18;</code>
     */
    @java.lang.Override

    public long getMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMap() {
      internalGetMutableMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18;</code>
     */

    public Builder removeMap(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long>
    getMutableMap() {
      return internalGetMutableMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18;</code>
     */
    public Builder putMap(
        java.lang.String key,
        long value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      internalGetMutableMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, int64&gt; map = 18;</code>
     */

    public Builder putAllMap(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      internalGetMutableMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<com.zwl.protocolbuffer.Result> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        results_ = new java.util.ArrayList<com.zwl.protocolbuffer.Result>(results_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zwl.protocolbuffer.Result, com.zwl.protocolbuffer.Result.Builder, com.zwl.protocolbuffer.ResultOrBuilder> resultsBuilder_;

    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public java.util.List<com.zwl.protocolbuffer.Result> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public com.zwl.protocolbuffer.Result getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder setResults(
        int index, com.zwl.protocolbuffer.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder setResults(
        int index, com.zwl.protocolbuffer.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder addResults(com.zwl.protocolbuffer.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder addResults(
        int index, com.zwl.protocolbuffer.Result value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder addResults(
        com.zwl.protocolbuffer.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder addResults(
        int index, com.zwl.protocolbuffer.Result.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends com.zwl.protocolbuffer.Result> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public com.zwl.protocolbuffer.Result.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public com.zwl.protocolbuffer.ResultOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public java.util.List<? extends com.zwl.protocolbuffer.ResultOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public com.zwl.protocolbuffer.Result.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          com.zwl.protocolbuffer.Result.getDefaultInstance());
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public com.zwl.protocolbuffer.Result.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, com.zwl.protocolbuffer.Result.getDefaultInstance());
    }
    /**
     * <code>repeated .com.zwl.protocolbuffer.Result results = 19;</code>
     */
    public java.util.List<com.zwl.protocolbuffer.Result.Builder> 
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zwl.protocolbuffer.Result, com.zwl.protocolbuffer.Result.Builder, com.zwl.protocolbuffer.ResultOrBuilder> 
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zwl.protocolbuffer.Result, com.zwl.protocolbuffer.Result.Builder, com.zwl.protocolbuffer.ResultOrBuilder>(
                results_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }

    private java.util.List<com.google.protobuf.Any> details_ =
      java.util.Collections.emptyList();
    private void ensureDetailsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        details_ = new java.util.ArrayList<com.google.protobuf.Any>(details_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;

    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public java.util.List<com.google.protobuf.Any> getDetailsList() {
      if (detailsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(details_);
      } else {
        return detailsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public int getDetailsCount() {
      if (detailsBuilder_ == null) {
        return details_.size();
      } else {
        return detailsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public com.google.protobuf.Any getDetails(int index) {
      if (detailsBuilder_ == null) {
        return details_.get(index);
      } else {
        return detailsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder setDetails(
        int index, com.google.protobuf.Any value) {
      if (detailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailsIsMutable();
        details_.set(index, value);
        onChanged();
      } else {
        detailsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder setDetails(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      if (detailsBuilder_ == null) {
        ensureDetailsIsMutable();
        details_.set(index, builderForValue.build());
        onChanged();
      } else {
        detailsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder addDetails(com.google.protobuf.Any value) {
      if (detailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailsIsMutable();
        details_.add(value);
        onChanged();
      } else {
        detailsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder addDetails(
        int index, com.google.protobuf.Any value) {
      if (detailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDetailsIsMutable();
        details_.add(index, value);
        onChanged();
      } else {
        detailsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder addDetails(
        com.google.protobuf.Any.Builder builderForValue) {
      if (detailsBuilder_ == null) {
        ensureDetailsIsMutable();
        details_.add(builderForValue.build());
        onChanged();
      } else {
        detailsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder addDetails(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      if (detailsBuilder_ == null) {
        ensureDetailsIsMutable();
        details_.add(index, builderForValue.build());
        onChanged();
      } else {
        detailsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder addAllDetails(
        java.lang.Iterable<? extends com.google.protobuf.Any> values) {
      if (detailsBuilder_ == null) {
        ensureDetailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, details_);
        onChanged();
      } else {
        detailsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder clearDetails() {
      if (detailsBuilder_ == null) {
        details_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        detailsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public Builder removeDetails(int index) {
      if (detailsBuilder_ == null) {
        ensureDetailsIsMutable();
        details_.remove(index);
        onChanged();
      } else {
        detailsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public com.google.protobuf.Any.Builder getDetailsBuilder(
        int index) {
      return getDetailsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
        int index) {
      if (detailsBuilder_ == null) {
        return details_.get(index);  } else {
        return detailsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
         getDetailsOrBuilderList() {
      if (detailsBuilder_ != null) {
        return detailsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(details_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public com.google.protobuf.Any.Builder addDetailsBuilder() {
      return getDetailsFieldBuilder().addBuilder(
          com.google.protobuf.Any.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public com.google.protobuf.Any.Builder addDetailsBuilder(
        int index) {
      return getDetailsFieldBuilder().addBuilder(
          index, com.google.protobuf.Any.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Any details = 20;</code>
     */
    public java.util.List<com.google.protobuf.Any.Builder> 
         getDetailsBuilderList() {
      return getDetailsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getDetailsFieldBuilder() {
      if (detailsBuilder_ == null) {
        detailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                details_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        details_ = null;
      }
      return detailsBuilder_;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private com.google.protobuf.Duration duration_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationBuilder_;
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     * @return Whether the duration field is set.
     */
    public boolean hasDuration() {
      return durationBuilder_ != null || duration_ != null;
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     * @return The duration.
     */
    public com.google.protobuf.Duration getDuration() {
      if (durationBuilder_ == null) {
        return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
      } else {
        return durationBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder setDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        duration_ = value;
        onChanged();
      } else {
        durationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder setDuration(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (durationBuilder_ == null) {
        duration_ = builderForValue.build();
        onChanged();
      } else {
        durationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder mergeDuration(com.google.protobuf.Duration value) {
      if (durationBuilder_ == null) {
        if (duration_ != null) {
          duration_ =
            com.google.protobuf.Duration.newBuilder(duration_).mergeFrom(value).buildPartial();
        } else {
          duration_ = value;
        }
        onChanged();
      } else {
        durationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public Builder clearDuration() {
      if (durationBuilder_ == null) {
        duration_ = null;
        onChanged();
      } else {
        duration_ = null;
        durationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public com.google.protobuf.Duration.Builder getDurationBuilder() {
      
      onChanged();
      return getDurationFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
      if (durationBuilder_ != null) {
        return durationBuilder_.getMessageOrBuilder();
      } else {
        return duration_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : duration_;
      }
    }
    /**
     * <code>.google.protobuf.Duration duration = 22;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getDurationFieldBuilder() {
      if (durationBuilder_ == null) {
        durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getDuration(),
                getParentForChildren(),
                isClean());
        duration_ = null;
      }
      return durationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.zwl.protocolbuffer.ProtoDemo)
  }

  // @@protoc_insertion_point(class_scope:com.zwl.protocolbuffer.ProtoDemo)
  private static final com.zwl.protocolbuffer.ProtoDemo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zwl.protocolbuffer.ProtoDemo();
  }

  public static com.zwl.protocolbuffer.ProtoDemo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoDemo>
      PARSER = new com.google.protobuf.AbstractParser<ProtoDemo>() {
    @java.lang.Override
    public ProtoDemo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoDemo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoDemo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoDemo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zwl.protocolbuffer.ProtoDemo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

