// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package com.zwl.protocolbuffer;

public interface ProtoDemoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProtoDemo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 int32 = 1;</code>
   * @return The int32.
   */
  int getInt32();

  /**
   * <code>int64 int64 = 2;</code>
   * @return The int64.
   */
  long getInt64();

  /**
   * <code>sint32 sint32 = 3;</code>
   * @return The sint32.
   */
  int getSint32();

  /**
   * <code>sint64 sint64 = 4;</code>
   * @return The sint64.
   */
  long getSint64();

  /**
   * <code>uint32 uint32 = 5;</code>
   * @return The uint32.
   */
  int getUint32();

  /**
   * <code>uint64 uint64 = 6;</code>
   * @return The uint64.
   */
  long getUint64();

  /**
   * <code>float float = 7;</code>
   * @return The float.
   */
  float getFloat();

  /**
   * <code>double double = 8;</code>
   * @return The double.
   */
  double getDouble();

  /**
   * <pre>
   *存储空间固定的数字类型
   * </pre>
   *
   * <code>fixed32 fixed32 = 9;</code>
   * @return The fixed32.
   */
  int getFixed32();

  /**
   * <code>fixed64 fixed64 = 10;</code>
   * @return The fixed64.
   */
  long getFixed64();

  /**
   * <code>sfixed32 sfixed32 = 11;</code>
   * @return The sfixed32.
   */
  int getSfixed32();

  /**
   * <code>sfixed64 sfixed64 = 12;</code>
   * @return The sfixed64.
   */
  long getSfixed64();

  /**
   * <code>bool bool = 13;</code>
   * @return The bool.
   */
  boolean getBool();

  /**
   * <code>string str = 14;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 14;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();

  /**
   * <code>bytes bytes = 15;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();

  /**
   * <code>string name = 16;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 16;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 16;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 17;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>int32 age = 17;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */
  int getMapCount();
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */
  boolean containsMap(
      java.lang.String key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Long>
  getMap();
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */
  java.util.Map<java.lang.String, java.lang.Long>
  getMapMap();
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */

  long getMapOrDefault(
      java.lang.String key,
      long defaultValue);
  /**
   * <code>map&lt;string, int64&gt; map = 18;</code>
   */

  long getMapOrThrow(
      java.lang.String key);

  /**
   * <code>repeated .Result results = 19;</code>
   */
  java.util.List<com.zwl.protocolbuffer.Result> 
      getResultsList();
  /**
   * <code>repeated .Result results = 19;</code>
   */
  com.zwl.protocolbuffer.Result getResults(int index);
  /**
   * <code>repeated .Result results = 19;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .Result results = 19;</code>
   */
  java.util.List<? extends com.zwl.protocolbuffer.ResultOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .Result results = 19;</code>
   */
  com.zwl.protocolbuffer.ResultOrBuilder getResultsOrBuilder(
      int index);

  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getDetailsList();
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  com.google.protobuf.Any getDetails(int index);
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  int getDetailsCount();
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDetailsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any details = 20;</code>
   */
  com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Timestamp timestamp = 21;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 21;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 21;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return Whether the duration field is set.
   */
  boolean hasDuration();
  /**
   * <code>.google.protobuf.Duration duration = 22;</code>
   * @return The duration.
   */
  com.google.protobuf.Duration getDuration();
  /**
   * <code>.google.protobuf.Duration duration = 22;</code>
   */
  com.google.protobuf.DurationOrBuilder getDurationOrBuilder();

  public com.zwl.protocolbuffer.ProtoDemo.OneCase getOneCase();
}
