// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.zwl.grpc;

/**
 * <pre>
 *定义rpc服务
 * </pre>
 *
 * Protobuf service {@code Greeter}
 */
public  abstract class Greeter
    implements com.google.protobuf.Service {
  protected Greeter() {}

  public interface Interface {
    /**
     * <pre>
     *简单的一元rpc
     * </pre>
     *
     * <code>rpc sayHello(.HelloRequest) returns (.HelloResponse);</code>
     */
    public abstract void sayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

    /**
     * <pre>
     *服务器流式rpc，客户端从返回的流中读取，直到没有消息
     * </pre>
     *
     * <code>rpc listSayHello(.HelloRequest) returns (stream .HelloResponse);</code>
     */
    public abstract void listSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

    /**
     * <pre>
     *客户端流式rpc，客户端写入消息，等待服务端读取消息返回响应
     * </pre>
     *
     * <code>rpc streamSayHello(stream .HelloRequest) returns (.HelloResponse);</code>
     */
    public abstract void streamSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

    /**
     * <pre>
     *双向流式rpc
     * </pre>
     *
     * <code>rpc sayHelloAll(stream .HelloRequest) returns (stream .HelloResponse);</code>
     */
    public abstract void sayHelloAll(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new Greeter() {
      @java.lang.Override
      public  void sayHello(
          com.google.protobuf.RpcController controller,
          com.zwl.grpc.HelloRequest request,
          com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
        impl.sayHello(controller, request, done);
      }

      @java.lang.Override
      public  void listSayHello(
          com.google.protobuf.RpcController controller,
          com.zwl.grpc.HelloRequest request,
          com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
        impl.listSayHello(controller, request, done);
      }

      @java.lang.Override
      public  void streamSayHello(
          com.google.protobuf.RpcController controller,
          com.zwl.grpc.HelloRequest request,
          com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
        impl.streamSayHello(controller, request, done);
      }

      @java.lang.Override
      public  void sayHelloAll(
          com.google.protobuf.RpcController controller,
          com.zwl.grpc.HelloRequest request,
          com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
        impl.sayHelloAll(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sayHello(controller, (com.zwl.grpc.HelloRequest)request);
          case 1:
            return impl.listSayHello(controller, (com.zwl.grpc.HelloRequest)request);
          case 2:
            return impl.streamSayHello(controller, (com.zwl.grpc.HelloRequest)request);
          case 3:
            return impl.sayHelloAll(controller, (com.zwl.grpc.HelloRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.zwl.grpc.HelloRequest.getDefaultInstance();
          case 1:
            return com.zwl.grpc.HelloRequest.getDefaultInstance();
          case 2:
            return com.zwl.grpc.HelloRequest.getDefaultInstance();
          case 3:
            return com.zwl.grpc.HelloRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.zwl.grpc.HelloResponse.getDefaultInstance();
          case 1:
            return com.zwl.grpc.HelloResponse.getDefaultInstance();
          case 2:
            return com.zwl.grpc.HelloResponse.getDefaultInstance();
          case 3:
            return com.zwl.grpc.HelloResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   *简单的一元rpc
   * </pre>
   *
   * <code>rpc sayHello(.HelloRequest) returns (.HelloResponse);</code>
   */
  public abstract void sayHello(
      com.google.protobuf.RpcController controller,
      com.zwl.grpc.HelloRequest request,
      com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

  /**
   * <pre>
   *服务器流式rpc，客户端从返回的流中读取，直到没有消息
   * </pre>
   *
   * <code>rpc listSayHello(.HelloRequest) returns (stream .HelloResponse);</code>
   */
  public abstract void listSayHello(
      com.google.protobuf.RpcController controller,
      com.zwl.grpc.HelloRequest request,
      com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

  /**
   * <pre>
   *客户端流式rpc，客户端写入消息，等待服务端读取消息返回响应
   * </pre>
   *
   * <code>rpc streamSayHello(stream .HelloRequest) returns (.HelloResponse);</code>
   */
  public abstract void streamSayHello(
      com.google.protobuf.RpcController controller,
      com.zwl.grpc.HelloRequest request,
      com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

  /**
   * <pre>
   *双向流式rpc
   * </pre>
   *
   * <code>rpc sayHelloAll(stream .HelloRequest) returns (stream .HelloResponse);</code>
   */
  public abstract void sayHelloAll(
      com.google.protobuf.RpcController controller,
      com.zwl.grpc.HelloRequest request,
      com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.zwl.grpc.Service.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sayHello(controller, (com.zwl.grpc.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.zwl.grpc.HelloResponse>specializeCallback(
            done));
        return;
      case 1:
        this.listSayHello(controller, (com.zwl.grpc.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.zwl.grpc.HelloResponse>specializeCallback(
            done));
        return;
      case 2:
        this.streamSayHello(controller, (com.zwl.grpc.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.zwl.grpc.HelloResponse>specializeCallback(
            done));
        return;
      case 3:
        this.sayHelloAll(controller, (com.zwl.grpc.HelloRequest)request,
          com.google.protobuf.RpcUtil.<com.zwl.grpc.HelloResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.zwl.grpc.HelloRequest.getDefaultInstance();
      case 1:
        return com.zwl.grpc.HelloRequest.getDefaultInstance();
      case 2:
        return com.zwl.grpc.HelloRequest.getDefaultInstance();
      case 3:
        return com.zwl.grpc.HelloRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.zwl.grpc.HelloResponse.getDefaultInstance();
      case 1:
        return com.zwl.grpc.HelloResponse.getDefaultInstance();
      case 2:
        return com.zwl.grpc.HelloResponse.getDefaultInstance();
      case 3:
        return com.zwl.grpc.HelloResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.zwl.grpc.Greeter implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void sayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.zwl.grpc.HelloResponse.class,
          com.zwl.grpc.HelloResponse.getDefaultInstance()));
    }

    public  void listSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.zwl.grpc.HelloResponse.class,
          com.zwl.grpc.HelloResponse.getDefaultInstance()));
    }

    public  void streamSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.zwl.grpc.HelloResponse.class,
          com.zwl.grpc.HelloResponse.getDefaultInstance()));
    }

    public  void sayHelloAll(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request,
        com.google.protobuf.RpcCallback<com.zwl.grpc.HelloResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.zwl.grpc.HelloResponse.class,
          com.zwl.grpc.HelloResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.zwl.grpc.HelloResponse sayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public com.zwl.grpc.HelloResponse listSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public com.zwl.grpc.HelloResponse streamSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException;

    public com.zwl.grpc.HelloResponse sayHelloAll(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.zwl.grpc.HelloResponse sayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.zwl.grpc.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance());
    }


    public com.zwl.grpc.HelloResponse listSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.zwl.grpc.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance());
    }


    public com.zwl.grpc.HelloResponse streamSayHello(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.zwl.grpc.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance());
    }


    public com.zwl.grpc.HelloResponse sayHelloAll(
        com.google.protobuf.RpcController controller,
        com.zwl.grpc.HelloRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.zwl.grpc.HelloResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(3),
        controller,
        request,
        com.zwl.grpc.HelloResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:Greeter)
}

